### ISSUE TITLE
Read-only file system when saving booking details json

### ISSUE THREAD

**Issue by sbstratos79** [Vishvajeet590/CowinPy-Andy#4]
![Screenshot_20210607-014432089](https://user-images.githubusercontent.com/4395586/120938819-762ec180-c732-11eb-8968-f9e18a97e710.jpg)

**Comment by Vishvajeet590** [comment]
Hi, @sbstratos79 I have added a feature to save information over so that the User can save multiple configurations and run. It can be a little sketchy as I am testing it you can download the beta version of apk from [here](https://github.com/Vishvajeet590/CowinPy-Andy/blob/master/APK/CowinPy%20Test.apk). If it stuck at the phone number during the execution of saved config then manually press enter, it will pick up from there.

 Please notify any error occurs.

**Comment by sbstratos79** [comment]
Just tested it and it's working now. Another suggestion. You should refresh the 'x' in the line "Next update in x seconds" instead of printing a new line for every second. It gets ugly very quickly this way. Pallupz's version runs on pc so it doesn't look that bad in landscape mode.

**Comment by sbstratos79** [comment]
And thanks for the work dude!

**Comment by Vishvajeet590** [comment]
> Just tested it and it's working now. Another suggestion. You should refresh the 'x' in the line "Next update in x seconds" instead of printing a new line for every second. It gets ugly very quickly this way. Pallupz's version runs on pc so it doesn't look that bad in landscape mode.

Haha I know that looks very ugly. In pc version it deletes "next update in x sec" line before printing for x-1 th sec line. But its not like python on pc. Here every print statement appends itself on Textview. So it remains there only. I will try to make it clean

**Comment by Vishvajeet590** [comment]
> And thanks for the work dude!

Thanks. You motivated me a little, It's my first open source project.
